"""Markdown → PDF export for analyst reports.

Uses ``fpdf2`` (pure Python, no system dependencies) to render the markdown
report into a clean letter-sized PDF. Because fpdf2's built-in Helvetica is
latin-1 only, we normalise common non-ASCII punctuation (em-dashes, smart
quotes, arrows, bullets) to ASCII equivalents before rendering. This keeps
the output readable while avoiding the need to ship a TTF unicode font.

The rendered PDF preserves the original markdown's structure: headings,
bold / italic, bullet / ordered lists, tables, horizontal rules.
"""

from __future__ import annotations

import logging
import unicodedata
from pathlib import Path

import markdown
from fpdf import FPDF

logger = logging.getLogger(__name__)


# ── Character normalisation ────────────────────────────────────────────────
# LLM-generated text tends to include "smart" Unicode punctuation that
# Helvetica (latin-1) can't render. Map the most common offenders to ASCII.
_ASCII_MAP = {
    "\u2014": "-",     # em dash —
    "\u2013": "-",     # en dash –
    "\u2212": "-",     # minus sign
    "\u2018": "'",     # left single quote
    "\u2019": "'",     # right single quote
    "\u201c": '"',     # left double quote
    "\u201d": '"',     # right double quote
    "\u2026": "...",   # ellipsis
    "\u2192": "->",    # right arrow →
    "\u2190": "<-",    # left arrow
    "\u2194": "<->",   # double arrow
    "\u21d2": "=>",    # rightwards double
    "\u2022": "*",     # bullet •
    "\u00b7": "*",     # middle dot
    "\u25e6": "*",     # white bullet
    "\u00a0": " ",     # nbsp
    "\u2009": " ",     # thin space
    "\u200b": "",      # zero-width space
    "\u2264": "<=",    # ≤
    "\u2265": ">=",    # ≥
    "\u2248": "~",     # ≈
    "\u00b1": "+/-",   # ±
    "\u00d7": "x",     # ×
    "\u00b0": " deg",  # °
    "\u20ac": "EUR",   # €
    "\u00a3": "GBP",   # £
    "\u00a5": "JPY",   # ¥
    "\u2122": "(TM)",  # ™
    "\u00ae": "(R)",   # ®
    "\u00a9": "(c)",   # ©
    "\u2713": "v",     # ✓
    "\u2717": "x",     # ✗
    "\u2022\u2022": "**",
}


def _to_latin1_safe(text: str) -> str:
    """Normalise a string so it can be encoded in latin-1 (fpdf2's default)."""
    for needle, rep in _ASCII_MAP.items():
        text = text.replace(needle, rep)
    # Strip combining marks and decompose accented chars to closest ASCII
    text = unicodedata.normalize("NFKD", text)
    # Drop anything still outside latin-1 as a last-resort fallback
    return text.encode("latin-1", errors="replace").decode("latin-1")


# ── PDF writer ─────────────────────────────────────────────────────────────

class _ReportPDF(FPDF):
    """Subclass that wires up a consistent footer (page numbers)."""

    def __init__(self, title: str) -> None:
        super().__init__(orientation="P", unit="mm", format="Letter")
        self.set_margins(left=18, top=18, right=18)
        self.set_auto_page_break(auto=True, margin=20)
        self._title = _to_latin1_safe(title)

    def footer(self) -> None:  # type: ignore[override]
        self.set_y(-14)
        self.set_font("Helvetica", size=8)
        self.set_text_color(130, 140, 160)
        self.cell(
            0,
            5,
            f"{self._title}   |   Page {self.page_no()}/{{nb}}",
            align="C",
        )


def render_markdown_to_pdf(md_text: str, title: str = "Analyst Report") -> bytes:
    """Render a markdown string into a PDF document.

    Args:
        md_text: The raw markdown text.
        title: Title used in the PDF header and footer.

    Returns:
        Raw PDF bytes suitable for returning in an HTTP response.
    """
    html = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code", "sane_lists"],
        output_format="html",
    )
    html_safe = _to_latin1_safe(html)

    pdf = _ReportPDF(title=title)
    pdf.alias_nb_pages()
    pdf.add_page()

    # Header block (runs once at the top of page 1)
    pdf.set_font("Helvetica", style="B", size=16)
    pdf.set_text_color(26, 29, 35)
    pdf.cell(0, 9, _to_latin1_safe(title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(130, 140, 160)
    pdf.cell(
        0,
        5,
        "Generated by Financial Analyst AI",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(3)
    pdf.set_draw_color(221, 225, 231)
    pdf.line(18, pdf.get_y(), pdf.w - 18, pdf.get_y())
    pdf.ln(4)

    # Body: feed the HTML to fpdf2's built-in renderer
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(26, 29, 35)
    # `write_html` gives us decent handling of <h1>-<h6>, <ul>, <ol>, <table>,
    # <strong>, <em>, <a>, <code>, <hr>, <blockquote>. Good enough for our
    # report shape without writing a bespoke parser.
    try:
        pdf.write_html(
            html_safe,
            table_line_separators=True,
        )
    except Exception as exc:
        logger.warning("write_html failed (%s) — falling back to plaintext", exc)
        pdf.set_font("Helvetica", size=10)
        pdf.multi_cell(0, 5, _to_latin1_safe(md_text))

    out = pdf.output()
    return bytes(out)


def render_markdown_file_to_pdf(md_path: Path, title: str | None = None) -> bytes:
    """Convenience wrapper: render a markdown file path to PDF bytes."""
    md_text = md_path.read_text(encoding="utf-8")
    return render_markdown_to_pdf(md_text, title=title or md_path.stem)
